--建立表User
--CREATE TABLE [User]
--(
--[Id] INT NOT NULL PRIMARY KEY,
--[UserName] NVARCHAR(20) NOT NULL,
--[Password] NVARCHAR(20) NOT NULL
--);
CREATE TABLE Problem
(
Id INT IDENTITY PRIMARY KEY,
Title NVARCHAR NOT NULL,
Content NTEXT NOT NULL,
NeedRemoteHelp BIT DEFAULT(1),
Reward TINYINT ,
PublishDateTime DATETIME NOT NULL
)